name: Build Action
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2022.3.6f1
        targetPlatform:
          - WebGL
          - StandaloneWindows64
        projectName:
          - Ballz
        projectPath:
          - ./Ballz
    steps:
      #Checking out the repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: false

      #Testing if caching is working
      - name: run
        run: ls

      #Caching
      - name: Caching
        uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
            Library-

      #Making the build.
      - name: Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}

      #Submitting to itch.io
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ballz
          ITCH_USER: ConnorY97
          PACKAGE: build/windows

      #Uploading the build to github.
      #- name: Uploading the build
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Build
      #    path: build

      