name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2022.3.6f1
        targetPlatform:
          - StandaloneWindows64
        projectName:
          - Ballz
        projectPath:
          - ./Ballz
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false
          
      - name: Caching
      - uses: actions/cache@v3
        with:
          path: ./Ballz/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: 
            Library-
            Library-Ballz-
            
      - name: Unity Builder
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: UnityBuilderAction.BuildScript.Build

      - name: Upload
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
