name: Build Action
on:
  push

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2022.3.6f1
        targetPlatform:
          - WebGL
        projectName:
          - Ballz
        projectPath:
          - ./Ballz
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Caching
        uses: actions/cache@v3
        with:
          path: ./Ballz/Library
          key: Library-${{matrix.projectName}}-${{matrix.targetPlatform}}
          restore-keys: |
            Library-${{matrix.projectName}}-
            Library-

      - name: Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Uploading the build
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

  download-project:
      name: Download Project
      runs-on: ubuntu-latest
      needs: build-project
      steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
            name: Build

  release-project:
      name: Release Project
      runs-on: ubuntu-latest
      needs: download-project
      steps:
      - name: Uploading to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ballz
          ITCH_USER: ConnorY97
          PACKAGE: /home/runner/work/Ballz/Ballz