name: Actions 😎

on: [push]

jobs:
  build:
    name: Testing License
    runs-on: ubuntu-latest
    steps:
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
